on:
#  pull_request:
#    branches:
#      - main
#      - master
#      - develop
  push:
    branches:
      - main
      - master
      - develop
name: "🚀 📱 Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest #macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'

        run: |
          touch .env &&
          echo FLUTTER_ENV=production >> .env
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.2'
      - run: flutter pub get
      - run: cp flutter_native_splash-storeone.yaml flutter_native_splash.yaml && dart run flutter_native_splash:create
      - run: flutter build apk --flavor storeone --dart-define=ENV=production -t lib/main_storeone.dart
      #- run: |
      #    flutter build ios --no-codesign
      #   cd build/ios/iphoneos
      #   mkdir Payload
      #   cd Payload
      #   ln -s ../Runner.app
      #   cd ..
      #   zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: storeone.${{ github.run_number }}
          token: ${{ secrets.PAT }}